<?php
require_once __DIR__ . '/config/bootstrap.php';
require_once __DIR__ . '/data/repository.php';
$user = require_role(['Administrador']);
$pdo = db(); $error = null;
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    verify_csrf();
    try {
        $action = $_POST['action'] ?? 'create';
        if ($action === 'create') { $category = trim($_POST['category'] ?? ''); $description = trim($_POST['description'] ?? ''); $amount = (float) ($_POST['amount'] ?? 0); $date = $_POST['expense_date'] ?? ''; if ($category === '' || $description === '' || $amount <= 0 || !preg_match('/^\d{4}-\d{2}-\d{2}$/', $date)) throw new InvalidArgumentException('Completa los datos del gasto con un monto y fecha válidos.'); $statement = $pdo->prepare('INSERT INTO expenses (user_id, category, description, amount, expense_date) VALUES (:user_id, :category, :description, :amount, :expense_date)'); $statement->execute(['user_id' => $user['id'], 'category' => $category, 'description' => $description, 'amount' => $amount, 'expense_date' => $date]); flash('success', 'Gasto registrado correctamente.'); redirect('gastos.php'); }
        if ($action === 'delete') { $statement = $pdo->prepare('DELETE FROM expenses WHERE id = :id'); $statement->execute(['id' => (int) $_POST['id']]); flash('success', 'Gasto eliminado.'); redirect('gastos.php'); }
    } catch (Throwable $exception) { $error = $exception->getMessage(); }
}
$expenses = expenses($pdo); $total = array_sum(array_column($expenses, 'amount')); $pageTitle = 'Gastos'; $activePage = 'gastos'; require __DIR__ . '/includes/header.php';
?>
<section class="page-heading"><div><p class="eyebrow">Egresos del negocio</p><h1>Gastos</h1><p class="muted">Registra y consulta los costos de tu operación.</p></div><div class="page-total"><small>Total registrado</small><strong><?= money($total) ?></strong></div></section><section class="content-grid expense-layout"><section class="panel form-panel"><div class="panel-heading"><div><p class="eyebrow">Nuevo movimiento</p><h2>Registrar gasto</h2></div></div><form id="gastoForm" class="form-grid" method="post"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="create"><label for="category">Categoría<input id="category" name="category" type="text" placeholder="Ej. Servicios" required></label><label for="description">Descripción<input id="description" name="description" type="text" placeholder="Describe el gasto" required></label><label for="amount">Monto<input id="amount" name="amount" type="number" step="0.01" placeholder="$ 0,00" required></label><label for="expense_date">Fecha<input id="expense_date" name="expense_date" type="date" value="<?= e(date('Y-m-d')) ?>" required></label><?php if ($error): ?><p class="error-message"><?= e($error) ?></p><?php endif; ?><button class="btn btn-primary" type="submit">Guardar gasto <span>→</span></button></form></section><section class="panel table-panel"><div class="panel-heading"><div><p class="eyebrow">Historial</p><h2>Gastos recientes</h2></div></div><div class="table-wrap"><table><thead><tr><th>Categoría</th><th>Descripción</th><th>Monto</th><th>Fecha</th><th></th></tr></thead><tbody id="gastosBody"><?php foreach ($expenses as $expense): ?><tr><td><span class="category-mark"></span><?= e($expense['category']) ?></td><td><?= e($expense['description']) ?></td><td><strong><?= money($expense['amount']) ?></strong></td><td><?= e($expense['expense_date']) ?></td><td><form class="inline-form" method="post" data-confirm="¿Eliminar este gasto?"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?= e($expense['id']) ?>"><button class="table-action danger" type="submit">Eliminar</button></form></td></tr><?php endforeach; ?><?php if (!$expenses): ?><tr><td colspan="5" class="empty-state">No hay gastos registrados.</td></tr><?php endif; ?></tbody></table></div></section></section>
<?php require __DIR__ . '/includes/footer.php'; ?>
