<?php
require_once __DIR__ . '/config/bootstrap.php';
require_once __DIR__ . '/data/repository.php';
$user = require_role(['Administrador', 'Repositor']);
$pdo = db();
$editing = null; $error = null;
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    verify_csrf();
    try {
        $action = $_POST['action'] ?? '';
        if ($action === 'save') {
            $name = trim($_POST['name'] ?? ''); $categoryId = (int) ($_POST['category_id'] ?? 0); $unit = trim($_POST['unit'] ?? 'unidad');
            $cost = (float) ($_POST['cost'] ?? 0); $price = (float) ($_POST['price'] ?? 0); $stock = (float) ($_POST['stock'] ?? 0); $minimum = (float) ($_POST['minimum_stock'] ?? 0); $id = (int) ($_POST['id'] ?? 0);
            if ($name === '' || !$categoryId || $cost < 0 || $price <= $cost || $stock < 0 || $minimum < 0) throw new InvalidArgumentException('Revisa los datos del producto y asegúrate de que el precio de venta sea mayor al costo.');
            if ($id) { $statement = $pdo->prepare('UPDATE products SET category_id = :category_id, name = :name, unit = :unit, cost = :cost, price = :price, stock = :stock, minimum_stock = :minimum_stock WHERE id = :id'); $statement->execute(['category_id' => $categoryId, 'name' => $name, 'unit' => $unit, 'cost' => $cost, 'price' => $price, 'stock' => $stock, 'minimum_stock' => $minimum, 'id' => $id]); }
            else { $statement = $pdo->prepare('INSERT INTO products (category_id, name, unit, cost, price, stock, minimum_stock) VALUES (:category_id, :name, :unit, :cost, :price, :stock, :minimum_stock)'); $statement->execute(['category_id' => $categoryId, 'name' => $name, 'unit' => $unit, 'cost' => $cost, 'price' => $price, 'stock' => $stock, 'minimum_stock' => $minimum]); }
            flash('success', $id ? 'Producto actualizado.' : 'Producto creado.'); redirect('inventario.php');
        }
        if ($action === 'delete') { $statement = $pdo->prepare('UPDATE products SET active = 0 WHERE id = :id'); $statement->execute(['id' => (int) $_POST['id']]); flash('success', 'Producto retirado del inventario.'); redirect('inventario.php'); }
    } catch (Throwable $exception) { $error = $exception->getMessage(); }
}
if (isset($_GET['edit'])) $editing = product($pdo, (int) $_GET['edit']);
$search = trim($_GET['q'] ?? ''); $products = products($pdo, $search); $categories = categories($pdo); $lowStock = low_stock($pdo);
$pageTitle = 'Inventario'; $activePage = 'inventario';
require __DIR__ . '/includes/header.php';
?>
<section class="page-heading"><div><p class="eyebrow">Catálogo y existencias</p><h1>Inventario</h1><p class="muted">Administra tus productos y mantén el stock bajo control.</p></div><button class="btn btn-primary" type="button" data-scroll-to="inventarioForm">+ Nuevo producto</button></section>
<div class="content-grid inventory-layout"><section class="panel form-panel"><div class="panel-heading"><div><p class="eyebrow"><?= $editing ? 'Editar registro' : 'Nuevo registro' ?></p><h2><?= $editing ? 'Editar producto' : 'Alta de producto' ?></h2></div></div><form id="inventarioForm" class="form-grid" method="post"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="save"><input type="hidden" name="id" value="<?= e($editing['id'] ?? '') ?>"><div class="form-row"><label for="name">Nombre<input id="name" name="name" type="text" value="<?= e($editing['name'] ?? '') ?>" placeholder="Ej. Café Premium" required></label><label for="category_id">Categoría<select id="category_id" name="category_id" required><option value="">Selecciona</option><?php foreach ($categories as $category): ?><option value="<?= e($category['id']) ?>" <?= (int) ($editing['category_id'] ?? 0) === (int) $category['id'] ? 'selected' : '' ?>><?= e($category['name']) ?></option><?php endforeach; ?></select></label></div><div class="form-row"><label for="cost">Precio costo<input id="cost" name="cost" type="number" step="0.01" value="<?= e($editing['cost'] ?? '') ?>" required></label><label for="price">Precio venta<input id="price" name="price" type="number" step="0.01" value="<?= e($editing['price'] ?? '') ?>" required></label></div><div class="form-row"><label for="unit">Unidad de medida<input id="unit" name="unit" type="text" value="<?= e($editing['unit'] ?? 'unidad') ?>" required></label><label for="stock">Stock actual<input id="stock" name="stock" type="number" step="0.001" value="<?= e($editing['stock'] ?? '') ?>" required></label></div><label for="minimum_stock">Stock mínimo<input id="minimum_stock" name="minimum_stock" type="number" step="0.001" value="<?= e($editing['minimum_stock'] ?? '') ?>" required></label><?php if ($error): ?><p class="error-message"><?= e($error) ?></p><?php endif; ?><button class="btn btn-primary" type="submit"><?= $editing ? 'Actualizar producto' : 'Guardar producto' ?> <span>→</span></button></form></section><section class="panel alert-panel inventory-alert"><div><p class="eyebrow">Atención</p><h2>Alertas de stock</h2></div><ul id="alertList" class="alert-list"><?php foreach ($lowStock as $item): ?><li><span class="status-dot critical"></span><span><strong><?= e($item['name']) ?></strong><small><?= e($item['stock']) ?> unidades · mínimo <?= e($item['minimum_stock']) ?></small></span><b>Revisar</b></li><?php endforeach; ?><?php if (!$lowStock): ?><li class="empty-state">No hay alertas activas.</li><?php endif; ?></ul></section></div>
<section class="panel table-panel"><div class="panel-heading"><div><p class="eyebrow">Vista general</p><h2>Listado de productos <span class="count-badge"><?= count($products) ?></span></h2></div><form class="table-tools" method="get"><input type="search" name="q" value="<?= e($search) ?>" placeholder="Buscar producto..." aria-label="Buscar producto"></form></div><div class="table-wrap"><table><thead><tr><th>Producto</th><th>Categoría</th><th>Precio venta</th><th>Stock</th><th>Mínimo</th><th>Estado</th><th>Acciones</th></tr></thead><tbody id="productosBody"><?php foreach ($products as $product): ?><tr><td><strong><?= e($product['name']) ?></strong><small><?= e($product['unit']) ?></small></td><td><?= e($product['category_name']) ?></td><td><?= money($product['price']) ?></td><td><?= e($product['stock']) ?></td><td><?= e($product['minimum_stock']) ?></td><td><span class="status-pill <?= $product['stock'] <= $product['minimum_stock'] ? 'status-low' : 'status-ok' ?>"><?= $product['stock'] <= $product['minimum_stock'] ? 'Stock bajo' : 'En stock' ?></span></td><td><a class="table-action" href="inventario.php?edit=<?= e($product['id']) ?>">Editar</a><form class="inline-form" method="post" data-confirm="¿Retirar este producto?"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?= e($product['id']) ?>"><button class="table-action danger" type="submit">Retirar</button></form></td></tr><?php endforeach; ?><?php if (!$products): ?><tr><td colspan="7" class="empty-state">No hay productos que coincidan con la búsqueda.</td></tr><?php endif; ?></tbody></table></div></section>
<?php require __DIR__ . '/includes/footer.php'; ?>
